name: attributed_text
description: Text with metadata spans for easy text editing and styling.
version: 0.1.0
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  flutter_lints: ^1.0.0
  logging: ^1.0.1
  test: ^1.19.4

dev_dependencies:
  mockito: ^5.0.4

